# Generated by Django 5.1.6 on 2025-02-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=255)),
                ('promotion_description', models.TextField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo'), ('2x1', '2x1')], max_length=50)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applicable_day', models.CharField(blank=True, max_length=20, null=True)),
                ('min_tickets', models.ImageField(blank=True, null=True, upload_to='')),
                ('card_type', models.CharField(blank=True, max_length=20, null=True)),
                ('days_before_function', models.ImageField(blank=True, null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
