# Generated by Django 5.1.6 on 2025-03-19 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_failed_attemps_customuser_is_locked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='failed_attemps',
            new_name='failed_attempts',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
