# Generated by Django 5.1.6 on 2025-02-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemainfo',
            name='ticket_price',
        ),
    ]
