# Generated by Django 5.1.6 on 2025-02-06 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_name', models.CharField(max_length=100)),
                ('combo_description', models.TextField()),
                ('combo_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('combo_picture', models.ImageField(upload_to='combos/')),
            ],
        ),
        migrations.CreateModel(
            name='ComboTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('total_combo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('combo_ticket_code', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo', to='bookings.booking')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.combo')),
            ],
        ),
    ]
