# Generated by Django 5.1.6 on 2025-02-06 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='function_time',
        ),
        migrations.AddField(
            model_name='function',
            name='function_time_start',
            field=models.TimeField(default=datetime.time),
        ),
    ]
