# Generated by Django 5.1.6 on 2025-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_classification_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('animacion', 'Animación'), ('comedia', 'Comedia'), ('crimen', 'Crimen'), ('documental', 'Documental'), ('drama', 'Drama'), ('familia', 'Familia'), ('fantasia', 'Fantasía'), ('historia', 'Historia'), ('terror', 'Terror'), ('musica', 'Música'), ('misterio', 'Misterio'), ('romance', 'Romance'), ('ciencia_ficcion', 'Ciencia Ficción'), ('deportes', 'Deportes'), ('suspenso', 'Suspenso'), ('guerra', 'Guerra'), ('western', 'Western')], max_length=50),
        ),
    ]
